"""Exact verification of Python radical expressions in a native Wolfram kernel.

Run ``python verify_wolfram.py`` (uses wolfram.exe from PATH or the default
Wolfram 15 installation directory), or ``python verify_wolfram.py --emit
check.wl`` to write the generated Wolfram script without running it.

The Wolfram side checks exactly, with RootReduce, that each expression is a
root of the minimal polynomial, and identifies the conjugate numerically at 60
digits against the value computed by Python (the roots are separated far
beyond that tolerance).  Root indices are not exchanged: Wolfram and Python
number non-real roots differently.  No package is loaded on the Wolfram side.
A failed check exits nonzero.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile

from flint import ctx

import roottoradicals as rt          # also puts the sibling engine on sys.path
import rootdecomp as rd

DEFAULT_WOLFRAM = r"C:\Program Files\Wolfram Research\Wolfram\15.0\wolfram.exe"

CASES = [
    ("sextic example", "Root[-1 - #^2 - #^3 + #^4 + #^6 &, 2]", {}),
    ("sextic example, conjugate 4", "Root[-1 - #^2 - #^3 + #^4 + #^6 &, 4]", {}),
    ("sextic example by descent", "Root[-1 - #^2 - #^3 + #^4 + #^6 &, 2]", {"method": "galois"}),
    ("quintic example", "Root[6 + 25 # - 25 #^3 + 5 #^5 &, 5]", {}),
    ("quintic example, conjugate 2", "Root[6 + 25 # - 25 #^3 + 5 #^5 &, 2]", {}),
    ("quintic example by descent", "Root[6 + 25 # - 25 #^3 + 5 #^5 &, 5]", {"method": "galois"}),
    ("cyclic quintic", "Root[1 + 3 # - 3 #^2 - 4 #^3 + #^4 + #^5 &, 1]", {}),
    ("cyclic quintic, eigenvector form", "Root[1 + 3 # - 3 #^2 - 4 #^3 + #^4 + #^5 &, 2]", {"resolvents": "eigenvector"}),
    ("x^3-3x+1 by descent", "Root[1 - 3 # + #^3 &, 1]", {"method": "galois"}),
    ("x^4-x-1 by descent", "Root[-1 - # + #^4 &, 1]", {"method": "galois"}),
    ("Phi_7 by descent", "Root[1 + # + #^2 + #^3 + #^4 + #^5 + #^6 &, 3]", {"method": "galois"}),
    ("decomposition (non-real root)", "Root[1 + 3 #^2 - 3 #^4 - 4 #^6 + #^8 + #^10 &, 5]", {}),
    ("Dickson D_7", "Root[-3 - 7 # + 14 #^3 - 7 #^5 + #^7 &, 1]", {}),
]


def _wolfram_value(z, digits=50):
    """A Wolfram number literal for the midpoint of the ball z."""
    re = z.real.mid().str(digits, radius=False)
    im = z.imag.mid().str(digits, radius=False)
    return f"(({re}) + ({im}) I)"


def make_script():
    rows = []
    for label, syntax, options in CASES:
        a = rd.parse_wolfram_root(syntax)
        result = rt.root_to_radicals(a, **options)
        print(f"Prepared {label}: method {result.method}, {result.leaf_count} leaves", flush=True)
        with ctx.workprec(400):
            value = _wolfram_value(a.value(400))
        poly = rd.wolfram_poly(a.poly).replace("#", "x")
        rows.append("{" + ", ".join([json.dumps(label), poly,
                                     "ToExpression[" + json.dumps(result.wolfram()) + "]", value]) + "}")
    return """(* Generated by python/verify_wolfram.py. No package is loaded. *)
rows = {
""" + ",\n".join(rows) + """
};
failures = 0;
Do[
  {label, poly, expr, value} = row;
  exact = Quiet[Check[RootReduce[poly /. x -> expr] === 0, False]];
  roots = Table[N[Root[Function @@ {poly /. x -> #}, k], 60], {k, Exponent[poly, x]}];
  near = Abs[N[expr, 60] - value] < 10^-30 && Count[roots, _?(Abs[# - value] < 10^-30 &)] == 1;
  ok = exact && near;
  Print[If[ok, "PASS ", "FAIL "], label, If[! exact, " (not a root)", ""], If[! near, " (wrong conjugate)", ""]];
  If[! ok, failures++],
  {row, rows}];
Print["failures: ", failures];
Exit[If[failures > 0, 1, 0]];
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", help="write the Wolfram script to this file instead of running it")
    ap.add_argument("--wolfram", help="path to wolfram.exe")
    args = ap.parse_args()
    script = make_script()
    if args.emit:
        with open(args.emit, "w", encoding="utf-8") as f:
            f.write(script)
        print("wrote", args.emit)
        return 0
    exe = args.wolfram or shutil.which("wolfram") or shutil.which("wolfram.exe") or DEFAULT_WOLFRAM
    if not os.path.exists(exe):
        print("no Wolfram kernel found; use --emit to write the script", file=sys.stderr)
        return 2
    with tempfile.TemporaryDirectory() as d:
        path = os.path.join(d, "check.wl")
        with open(path, "w", encoding="utf-8") as f:
            f.write(script)
        proc = subprocess.run([exe, "-noprompt", "-script", path], capture_output=True, text=True, timeout=1800)
    print(proc.stdout)
    if proc.returncode != 0:
        print(proc.stderr, file=sys.stderr)
    return proc.returncode


if __name__ == "__main__":
    sys.exit(main())
