"""Check Python chains, pairs, and certificates in a native Wolfram kernel.

Run ``python verify_wolfram.py`` or use ``--emit checks.wl`` to prepare a
standalone script. The generated script independently recomposes Python
chains using polynomial substitution and exact RootReduce. It also compares
both implementations' complete normalized chain sets and pairs, and feeds
Python's positive and negative certificates to the independent Wolfram
certificate checker. No floating-point conversion or built-in Decompose is
used. Requires a licensed native kernel; tests run in one kernel session.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import subprocess
import tempfile

import sympy as sp
from sympy.printing.mathematica import mathematica_code

import algebraic_decompose as ad


X = sp.Symbol('x')
ALPHA = sp.CRootOf(X**5 - X - 1, 0)  # The unique real root in both systems.
FIELD_SYMBOL = sp.Symbol('crossCheckAlpha')
KEYS = {
    'type': 'Type', 'right_degree': 'RightDegree', 'outer_degree': 'OuterDegree',
    'inner': 'Inner', 'outer_candidate': 'OuterCandidate', 'digits': 'Digits',
    'decomposable': 'Decomposable', 'obstruction': 'Obstruction', 'residual': 'Residual',
    'digit_index': 'DigitIndex', 'power': 'Power', 'coefficient': 'Coefficient',
    'input_degree': 'InputDegree', 'tested_right_degrees': 'TestedRightDegrees',
    'accepted_right_degrees': 'AcceptedRightDegrees', 'indecomposable': 'Indecomposable',
    'tests': 'Tests',
}


def wolfram(value):
    """Serialize our exact test data, including the shared real quintic root."""
    if value is None:
        return 'None'
    if value is True:
        return 'True'
    if value is False:
        return 'False'
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, (list, tuple)):
        return '{' + ','.join(map(wolfram, value)) + '}'
    if isinstance(value, dict):
        entries = []
        for key, item in value.items():
            serialized = ('Missing["NotApplicable","DegreeBelowTwo"]'
                          if key == 'indecomposable' and item is None else wolfram(item))
            entries.append(json.dumps(KEYS.get(key, key)) + '->' + serialized)
        return '<|' + ','.join(entries) + '|>'
    return mathematica_code(sp.sympify(value).xreplace({ALPHA: FIELD_SYMBOL}))


def corpus():
    x, s = X, sp.sqrt(2)
    p = (3 + 3*s + (14+4*s)*x + (12+26*s)*x**2 + (56+8*s)*x**3
         + (8+48*s)*x**4 + 48*x**5 + 16*s*x**6)
    h = x**2 + x
    yield 'question sextic', p
    yield 'nested degree 24', sp.expand(p.subs(x, x**4-x+1))
    yield 'sparse inner regression', (x**4+x)**2
    yield 'negative h-adic digits', h**3 + x*h
    yield 'power collisions', x**12
    yield 'Chebyshev collisions', sp.chebyshevt(12, x)
    yield 'generic indecomposable', x**12+x
    yield 'prime degree', x**7+s*x+1
    yield 'complex coefficients', (x**2+(s+sp.I)*x)**3+sp.I*(x**2+(s+sp.I)*x)+1
    h = x**3+(s+sp.sqrt(3))*x
    yield 'multiple quadratic generators', h**4+sp.sqrt(3)*h+1
    h = x**2+ALPHA*x
    yield 'irreducible quintic coefficient', h**3+ALPHA*h+1
    yield 'leading coefficient cancellation', (ALPHA**5-ALPHA-1)*x**6+(x**2+x)**2
    yield 'zero', sp.S.Zero
    yield 'constant', sp.sqrt(3)
    yield 'linear', s*x+sp.I


def make_script():
    rows = []
    for label, polynomial in corpus():
        chain = ad.decompose(polynomial, X)
        chains = ad.decompositions(polynomial, X)
        pairs = ad.decomposition_pairs(polynomial, X)
        certificate = ad.decomposition_data(polynomial, X)
        assert ad.verify_decomposition(polynomial, chain, X,
                                       require_complete=True, require_normalized=True), label
        assert ad.verify_decomposition_data(polynomial, certificate, X), label
        rows.append(wolfram({'Label': label, 'Input': polynomial, 'Chain': chain,
                             'AllChains': chains, 'Pairs': pairs, 'Certificate': certificate}))
        print(f'Prepared {label}: {len(chains)} complete chain(s), {len(pairs)} pair(s)', flush=True)
    package = Path(__file__).resolve().parents[1] / 'AlgebraicDecomposition.wl'
    return ('(* Generated by python/verify_wolfram.py. *)\n'
            'Get[' + json.dumps(package.as_posix()) + '];\n'
            'crossCheckAlpha = Root[#^5-#-1&,1];\nrows = {\n'
            + ',\n'.join(rows) + '\n};\n' + r'''
canonical[p_] := Module[{c = RootReduce /@ CoefficientList[Expand[p],x]},
  If[c === {}, c = {0}];
  While[Length[c]>1 && Last[c]===0, c=Most[c]];
  c];
same[a_,b_] := canonical[a-b] === {0};
chainCompose[parts_List] := Fold[Expand[#1 /. x -> #2]&,x,parts];
chainKey[parts_List] := canonical /@ parts;
setKey[chains_List] := Sort[chainKey /@ chains];
failures = 0;
Do[
  checks = Quiet[Check[Module[{p=row["Input"], chain=row["Chain"], chains=row["AllChains"],
      pairs=row["Pairs"], certificate=row["Certificate"], native},
    native = AlgebraicDecompositions[p,x];
    <|"independent recomposition" -> (same[p,chainCompose[chain]] &&
          AllTrue[chains, same[p,chainCompose[#]]&] &&
          AllTrue[pairs, same[p,chainCompose[#]]&]),
      "complete normalized Python chain" -> VerifyAlgebraicDecomposition[p,chain,x,
          "RequireComplete"->True,"RequireNormalized"->True],
      "one-chain parity" -> (chainKey[chain] === chainKey[AlgebraicDecompose[p,x]]),
      "all-chain parity" -> (ListQ[native] && setKey[chains] === setKey[native]),
      "pair parity" -> (setKey[pairs] === setKey[AlgebraicDecompositionPairs[p,x]]),
      "independent Python-certificate check" -> VerifyAlgebraicDecompositionData[p,certificate,x]
    |>], <|"evaluation"->False|>]];
  failed = Keys[Select[checks, !TrueQ[#]&]];
  Print[If[failed === {}, "PASS ", "FAIL "], row["Label"],
        If[failed === {}, "", ": "<>ToString[failed,InputForm]]];
  If[failed =!= {}, failures++],
  {row,rows}];
Print["Cross-language corpus: ",Length[rows]," cases, ",failures," failed."];
Exit[If[failures===0,0,1]];
''')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--emit', type=Path, help='write the standalone Wolfram check without running it')
    parser.add_argument('--wolfram', help='native kernel executable (not WolframScript)')
    parser.add_argument('--timeout', type=float, default=300, help='kernel timeout in seconds')
    args = parser.parse_args()
    kernel = args.wolfram or shutil.which('wolfram') or shutil.which('math')
    if not args.emit and not kernel:
        parser.error('No native Wolfram kernel found; supply --wolfram or use --emit')
    script = make_script()
    if args.emit:
        args.emit.write_text(script, encoding='utf-8')
        print(f'Wrote {args.emit.resolve()}')
        return 0
    with tempfile.TemporaryDirectory(prefix='polynomial-decompose-cross-') as directory:
        script_path = Path(directory) / 'verify.wl'
        script_path.write_text(script, encoding='utf-8')
        return subprocess.run([kernel, '-script', str(script_path)],
                              timeout=args.timeout, check=False).returncode


if __name__ == '__main__':
    raise SystemExit(main())
