"""Independently check Python decompositions in a native Wolfram kernel.

Run ``python verify_wolfram.py`` (requires wolfram.exe or math on PATH), or
``python verify_wolfram.py --emit review.wl`` to generate a standalone check.
The Wolfram side uses RootReduce and MinimalPolynomial directly; it does not
load the Wolfram decomposition implementation. A failed check exits nonzero.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import subprocess
import tempfile

from flint import fmpz_poly

import rootdecomp as rd


def cases():
    """Representative identities, including restricted and complex outputs."""
    examples = [
        ("product example", "Root[-1-#+3#^3-#^4+#^5-3#^6+2#^7+#^9&,1]",
         rd.product_decomposition, {}, 3, None),
        ("sum example", "Root[8-4#+24#^2-15#^3+3#^5+6#^6+#^9&,1]",
         rd.sum_decomposition, {}, 3, None),
        ("sextic sum outside the input field", "Root[-1-#+3#^3-#^4+#^5-3#^6+2#^7+#^9&,1]",
         rd.sum_decomposition, {"engine": "splitting"}, 6, None),
        ("input-field additive optimum", "Root[-1-#+3#^3-#^4+#^5-3#^6+2#^7+#^9&,1]",
         rd.sum_decomposition, {"scope": "InputField"}, 9, None),
        ("affine sum with two terms", "Root[-8+16#-4#^2-4#^3+#^4&,4]",
         rd.sum_decomposition, {"max_terms": 2}, 2, 2),
        ("three quadratic tensor factors", "Root[4096+4096#-16384#^2+6144#^3+3008#^4-768#^5-256#^6-8#^7+#^8&,8]",
         rd.product_decomposition, {"dmax": 2, "max_factors": 3, "depth": 0}, 2, 3),
        ("external quartic factors", "Root[4-8#^2-16#^4-4#^6+#^8&,4]",
         rd.product_decomposition, {"max_factors": 2, "engine": "splitting"}, 4, 2),
        ("quartic summands of a sextic", "Root[-1+4#^2+#^6&,3]",
         rd.sum_decomposition, {"engine": "splitting"}, 4, None),
    ]
    for label, syntax, fn, options, degree, count in examples:
        target = rd.parse_wolfram_root(syntax)
        result = fn(target, **options)
        if result is None or result.max_degree != degree:
            raise AssertionError(f"{label}: expected maximum degree {degree}, got {result}")
        if count is not None and len(result.terms) > count:
            raise AssertionError(f"{label}: exceeded {count} components")
        print(f"Prepared {label}: degrees {result.degrees}", flush=True)
        yield label, target, result

    # Each branch of sqrt(3) +/- i*sqrt(2), with both real-part signs.
    # This exercises the interchange ordering beyond real article examples.
    for index in range(1, 5):
        target = rd.AlgebraicNumber(fmpz_poly([25, 0, -2, 0, 1]), index)
        result = rd.sum_decomposition(target, max_terms=2)
        if result is None or result.max_degree != 2 or len(result.terms) > 2:
            raise AssertionError(f"complex branch {index}: {result}")
        yield f"complex branch {index}", target, result


def make_script():
    rows = []
    for label, target, result in cases():
        terms = "{" + ",".join(t.wolfram() for t in result.terms) + "}"
        degrees = "{" + ",".join(map(str, result.degrees)) + "}"
        rows.append("{" + ",".join([
            json.dumps(label), target.wolfram(), terms, result.op, degrees,
        ]) + "}")
    return """(* Generated by python/verify_wolfram.py. No package is loaded. *)
rows = {
""" + ",\n".join(rows) + """
};
failures = 0;
Do[
  ok = Quiet[Check[
    RootReduce[row[[2]] - Apply[row[[4]], row[[3]]]] === 0 &&
      (Exponent[MinimalPolynomial[#, x], x] & /@ row[[3]]) === row[[5]],
    False]];
  Print[If[TrueQ[ok], "PASS ", "FAIL "], row[[1]]];
  If[! TrueQ[ok], failures++],
  {row, rows}];
Print["Exact cross-language checks: ", Length[rows], ", failed: ", failures];
Exit[If[failures == 0, 0, 1]];
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", type=Path, help="write the Wolfram script without running it")
    parser.add_argument("--wolfram", help="native kernel executable (not WolframScript)")
    parser.add_argument("--timeout", type=float, default=300, help="kernel timeout in seconds")
    args = parser.parse_args()
    kernel = args.wolfram or shutil.which("wolfram") or shutil.which("math")
    if not args.emit and not kernel:
        parser.error("No native Wolfram kernel found; supply --wolfram or use --emit")
    script = make_script()
    if args.emit:
        args.emit.write_text(script, encoding="utf-8")
        print(f"Wrote {args.emit.resolve()}")
        return 0
    with tempfile.TemporaryDirectory(prefix="rootdecomp-exact-") as directory:
        path = Path(directory) / "verify.wl"
        path.write_text(script, encoding="utf-8")
        result = subprocess.run([kernel, "-script", str(path)], timeout=args.timeout, check=False)
        return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
